//...
std::vector<tfloat> PrefixOdds;
//...
tfloat p(tint l, tint r) { // Probabilidad de que no este en [l, r]
  return 1 - (PrefixOdds[r+1] - PrefixOdds[l]);
}
//...
int main(void) {
  //...
  PrefixOdds.resize(N+1, 0);
  forn(i, N) PrefixOdds[i+1] = PrefixOdds[i] + odds[i];
  //...
}
